# Application Configuration
env: dev
log_level: ""
frontend_url: "http://localhost:5173"
logfire_token: null
tz: "UTC"
secret_key: "your-secret"

database:
  url: "postgresql+asyncpg://postgres:123@localhost:5432/template-testing"

admin:
  username: "admin"
  password: "123"

celery:
  rabbitmq_url: null
